version: '2'
services:
    http-server:
        image: "harshals/http_server:development"
        ports:
         - "9000:9000"
         - "443:443"
        hostname: http-server
    mysql:
        image: "mysql/mysql-server"
        ports:
         - "3306:3306"
        hostname: mysql
        environment:
         - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
         - "MYSQL_ROOT_HOST=%"
    redis:
        image: "redis"
        ports:
         - "6379:6379"
        hostname: redis
    thrift-server:
        image: "harshals/thrift_server"
        ports:
         - "9090:9090"
        hostname: thrift-server
    postgres:
        image: "postgres"
        ports:
        - "5432:5432"
        hostname: postgres
    memcached:
        image: memcached
        ports:
        - "11211:11211"
        hostname: memcached
    client:
        image: "harshals/netsil_client:development"
        volumes:
         - /client/requests.json:/config/requests.json
        environment:
         - "DEMO_APP_HOST=http-server"
         - "MYSQL_HOST=mysql"
         - "REDIS_HOST=redis"
         - "THRIFT_SERVER=thrift-server"
         - "POSTGRES_HOST=postgres"
         - "MEMCACHED_HOST=memcached"
        command: >
           /bin/bash -c "
           while ! nc -z mysql 3306;
           do
             echo sleeping;
             sleep 1;
            done;
            echo Connected!;
            python client.py
           "