version: '2'
services:
    http-server:
        image: "harshals/http_server"
        ports:
         - "9000:9000"
        hostname: http-server
    mysql:
        image: "mysql/mysql-server"
        ports:
         - "3306:3306"
        hostname: mysql-server
        environment:
         - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
        command: "/bin/bash -c sleep 5; nc -lk 0.0.0.0 3306"
    redis:
        image: "redis"
        ports:
         - "6379:6379"
        hostname: redis-service
    thrift-server:
        image: "harshals/thrift_server"
        ports:
         - "9090:9090"
        hostname: thrift-server
    client:
        image: "harshals/netsil_client"
        environment:
         - "DEMO_APP_HOST=http-server"
         - "MYSQL_HOST=mysql-server"
         - "REDIS_HOST=redis-service"
         - "THRIFT_SERVER=thrift-server"
        command: 'nc -vz web 3306'
        command: 'nc -vz web 9000'
        command: 'nc -vz web 6379'
        command: 'nc -vz web 9090'