apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netsil-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: netsil
    spec:
      containers:
      - name: netsil-client
        image: harshals/netsil_client
        ports:
        - containerPort: 80
        - containerPort: 9000
        - containerPort: 3306
        - containerPort: 6379
        env:
        - name: DEMO_APP_HOST
          value: "http.netsil.io"
        - name: MYSQL_HOST
          value: "mysql.netsil.io"
        - name: REDIS_HOST
          value: "redis.netsil.io"