kind: ConfigMap
apiVersion: v1
metadata:
  name: http-error-workload
  namespace: default
data:
  # example of a complex property defined using --from-file
  requests.json: |
    {
       "mysql": [
        {
            "command": "INSERT INTO employee (fname, lname) VALUES ('first name', 'last name')",
            "count": "10"
        },
        {
             "command": "select * from employee",
             "count": "10"
        }
        ],
        "http":[
        {
            "success": {
                "count": "3"
            },
            "errors": [
                {
                    "http_code": "403",
                    "count": "30"
                },
                {
                    "http_code": "304",
                    "count": "30"
                },
                {
                    "http_code": "305",
                    "count": "40"
                }
            ]
        }
        ],
        "dynamodb": {
            "recordCount": "100",
            "isAWS": false,
            "AWS": {
                "region": "us-west-2",
                "accessKey": "123456789",
                "secretKey": "123456789"
            }
        }
    }