apiVersion: v1
kind: ReplicationController
metadata:
  name: http-client
spec:
  replicas: 2
  template:
    metadata:
      name: http-client
      labels:
        app: http-client
    spec:
      containers:
      - name: http-client
        image: harshals/http_client
        ports:
        - containerPort: 9000
        env:
        - name: DEMO_APP_HOST
          value: 10.254.119.116
