apiVersion: v1
kind: ReplicationController
metadata:
  name: http-server
spec:
  replicas: 2
  template:
    metadata:
      name: http-server
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: harshals/http_server
        ports:
        - containerPort: 9000
        env:
        - name: DEMO_APP_HOST
          value: 10.254.119.116
