apiVersion: v1
kind: Service
metadata:
  labels:
    name: mysql-server
  name: mysql-server
spec:
  type: ExternalName
  externalName: mysql.netsil.io
  ports:
    # The port that this service should serve on.
    - port: 3306
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: mysql-server
  type: LoadBalancer