apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
      - name: mysql-server
        image: mysql/mysql-server
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: yes