apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netsil-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: netsil
    spec:
      containers:
      - name: netsil-client
        image: harshals/netsil_client
        ports:
        - containerPort: 80
        - containerPort: 9000
        - containerPort: 3306
        - containerPort: 6379
        - containerPort: 443
        env:
        - name: DEMO_APP_HOST
          value: "http-server"
        - name: MYSQL_HOST
          value: "mysql-server"
        - name: REDIS_HOST
          value: "redis-service"
        - name: "POSTGRES_HOST"
          value: "postgres-server"
        - name: THRIFT_SERVER
          value: "thrift-server"
        - name: DYNAMODB_HOST
          value: "dynamodb"
        - name: MEMCACHED_HOST
          value: "memcached-server"
        - name: CASSANDRA_HOST
          value: "cassandra-server"
        - name: DEMO_APP_INTERMEDIATE_HOST
          value: "intermediate-http-service"
        - name: DEMO_CONFIG_FILE
          value: "/config/requests.json"
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      # consume the file-like keys of the configmap via volume plugin
      - name: config-volume
        configMap:
          name: http-error-workload