apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: harshals/http_server
        ports:
        - containerPort: 9000
          name: http-port
        - containerPort: 443
          name: https-port