apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: intermediate-http-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: intermediate-http-server
    spec:
      containers:
      - name: intermediate-http-server
        image: harshals/intermediate_server:development
        ports:
        - containerPort: 9010
          name: http-port
        env:
        - name: DEMO_APP_HOST
          value: "http-server"
