apiVersion: v1
kind: Service
metadata:
  labels:
    name: dynamodb
  name: dynamodb
spec:
  type: ExternalName
  externalName: dynamodb.netsil.io
  ports:
    # The port that this service should serve on.
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: dynamodb
  type: LoadBalancer