apiVersion: v1
kind: Service
metadata:
  labels:
    name: http-server
  name: http-server
spec:
  type: ExternalName
  externalName: http.netsil.io
  ports:
    # The port that this service should serve on.
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: http-server
  type: LoadBalancer