apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres-server
  name: postgres-server
spec:
  type: ExternalName
  externalName: postgres.netsil.io
  ports:
    # The port that this service should serve on.
    - port: 5432
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: postgres
  type: LoadBalancer