apiVersion: v1
kind: Service
metadata:
  labels:
    name: thrift-server
  name: thrift-server
spec:
  type: ExternalName
  externalName: http.netsil.io
  ports:
    # The port that this service should serve on.
    - port: 9090
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: thrift-server
  type: LoadBalancer